[enh] Ask to install CardDAV plugin with presets for Baïkal and ownCloud

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -9,6 +9,7 @@ app=$YNH_APP_INSTANCE_NAME
 # Retrieve arguments
 domain=$1
 path=${2%/}
+with_carddav=$3
 
 # Load common variables
 . ./_common.sh
@@ -40,8 +41,8 @@ deskey=$(ynh_string_random 24)
 dbpass=$(ynh_string_random)
 
 # Initialize database
-ynh_mysql_create_db $dbname $dbuser $dbpass
-ynh_mysql_connect_as $dbuser $dbpass $dbname \
+ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
+ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" \
     < "${TMPDIR}/SQL/mysql.initial.sql"
 
 # Copy and set Roundcube configuration
@@ -68,31 +69,16 @@ exec_composer www-data "$DESTDIR" require \
     "sblaisot/automatic_addressbook"
 installed_plugins+=" 'contextmenu', 'automatic_addressbook',"
 
+# Instal CardDAV plugin
+if [[ $with_carddav -eq 1 ]]; then
+  install_carddav "$DESTDIR" \
+    && installed_plugins+=" 'carddav'," \
+    || echo "Unable to install CardDAV plugin" >&2
+fi
+
 # Update Roundcube configuration
 sudo sed -i "s#^\s*// installed plugins#&\n ${installed_plugins}#" \
     "${DESTDIR}/config/config.inc.php"
-
-## Install rcmcarddav TODO: if baikal is detected
-#sudo yunohost app list -f baikal --json | grep '"installed": true'
-#if [ "$?" -eq 0 ]; then
-#  echo "Detected Baikal"
-#
-#  caldavdomain=$(sudo yunohost app setting baikal domain)
-#  caldavpath=$(sudo yunohost app setting baikal path)
-#  caldavpath=${caldavpath%/}
-#
-#  sed -i "s@yuno_baikal_domain@$caldavdomain@g" ../conf/rcmcarddav.config.inc.php
-#  sed -i "s@yuno_baikal_path@$caldavpath@g" ../conf/rcmcarddav.config.inc.php
-#  sudo cp ../conf/rcmcarddav.config.inc.php $final_path/plugins/carddav/config.inc.php
-#
-#  sudo sed -i "s@yuno_enable_carddav@True@g" $final_path/config/main.inc.php
-#
-#  mysql -u $dbuser -p$dbpass $dbname < ../sources/plugins/carddav/dbinit/mysql-drop.sql
-#  mysql -u $dbuser -p$dbpass $dbname < ../sources/plugins/carddav/dbinit/mysql.sql
-#else
-#  mysql -u $dbuser -p$dbpass $dbname < ../sources/plugins/carddav/dbinit/mysql-drop.sql
-#  sudo sed -i "s@yuno_enable_carddav@False@g" $final_path/config/main.inc.php
-#fi
 
 # Copy and set nginx configuration
 nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
@@ -109,7 +95,8 @@ sudo chown root: $phpfpm_conf
 sudo chmod 644 $phpfpm_conf
 
 # Save app settings
-ynh_app_setting_set $app mysqlpwd $dbpass
+ynh_app_setting_set "$app" with_carddav "$with_carddav"
+ynh_app_setting_set "$app" mysqlpwd "$dbpass"
 
 # Reload services
 sudo service php5-fpm restart || true
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -21,6 +21,7 @@ domain=$(ynh_app_setting_get "$app" domain)
 path=$(ynh_app_setting_get "$app" path)
 path=${path%/}
 dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
+with_carddav=$(ynh_app_setting_get "$app" with_carddav)
 
 # Check destination directory
 DESTDIR="/var/www/$app"
@@ -72,31 +73,24 @@ exec_composer www-data "$DESTDIR" require \
     "sblaisot/automatic_addressbook"
 installed_plugins+=" 'contextmenu', 'automatic_addressbook',"
 
+# Guess with_carddav value if empty
+if [[ -z "${with_carddav:-}" ]]; then
+  [[ -d "${DESTDIR}/plugins/carddav" ]] \
+    && with_carddav=1 \
+    || with_carddav=0
+  ynh_app_setting_set "$app" with_carddav "$with_carddav"
+fi
+
+# Update or instal CardDAV plugin
+if [[ $with_carddav -eq 1 ]]; then
+  install_carddav "$DESTDIR" \
+    && installed_plugins+=" 'carddav'," \
+    || echo "Unable to install CardDAV plugin" >&2
+fi
+
 # Update Roundcube configuration
 sudo sed -i "s#^\s*// installed plugins#&\n ${installed_plugins}#" \
     "$rc_conf"
-
-## Install rcmcarddav if baikal is detected
-#sudo yunohost app list -f baikal --json | grep '"installed": true'
-#if [ "$?" -eq 0 ]; then
-#  echo "Detected Baikal"
-#
-#  caldavdomain=$(sudo yunohost app setting baikal domain)
-#  caldavpath=$(sudo yunohost app setting baikal path)
-#  caldavpath=${caldavpath%/}
-#
-#  sed -i "s@yuno_baikal_domain@$caldavdomain@g" ../conf/rcmcarddav.config.inc.php
-#  sed -i "s@yuno_baikal_path@$caldavpath@g" ../conf/rcmcarddav.config.inc.php
-#  sudo cp ../conf/rcmcarddav.config.inc.php $final_path/plugins/carddav/config.inc.php
-#
-#  sudo sed -i "s@yuno_enable_carddav@True@g" $final_path/config/main.inc.php
-#
-#  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql-drop.sql
-#  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql.sql
-#else
-#  mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/carddav/dbinit/mysql-drop.sql
-#  sudo sed -i "s@yuno_enable_carddav@False@g" $final_path/config/main.inc.php
-#fi
 
 # Copy and set nginx configuration
 nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
