[fix] Update new version & script

diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,5 +1,86 @@
 #!/bin/bash
 
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -eu
+
+if [ ! -e _common.sh ]; then
+	# Get file fonction if not been to the current directory
+	sudo cp ../settings/scripts/_common.sh ./_common.sh
+	sudo chmod a+rx _common
+fi
+# Loads the generic functions usually used in the script
+source _common.sh
+# Source app helpers
+source /usr/share/yunohost/helpers
+
+app=$YNH_APP_INSTANCE_NAME
+
+# Retrieve arguments
+domain=$(ynh_app_setting_get "$app" domain)
+path=$(ynh_app_setting_get "$app" path)
+with_carddav=$(ynh_app_setting_get "$app" with_carddav)
+dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
+dbname=$app
+dbuser=$app
+
+# Check domain/path availability
+sudo yunohost app checkurl "${domain}${path}" -a "$app" \
+    || ynh_die "Path not available: ${domain}${path}"
+
+# Check $final_path
+final_path="/var/www/${app}"
+if [ -d $final_path ]; then
+	ynh_die "There is already a directory: $final_path"
+fi
+
+# Check configuration files
+nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
+if [ -f $nginx_conf ]; then
+	ynh_die "The NGINX configuration already exists at '${nginx_conf}'. 
+	You should safely delete it before restoring this app."
+fi
+# Check configuration files php-fpm
+phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"
+if [ -f $phpfpm_conf ]; then 
+	ynh_die "The PHP FPM configuration already exists at '${phpfpm_conf}'. 
+	You should safely delete it before restoring this app."
+fi
+
+phpfpm_ini="/etc/php5/fpm/conf.d/20-${app}.ini"
+if [ -f $phpfpm_ini ]; then
+	ynh_die "The PHP FPM INI configuration already exists at '${phpfpm_ini}'. 
+	You should safely delete it before restoring this app."
+fi
+
+# Create system user dedicace for this app
+ynh_system_user_create $app
+
+# Restore sources & data
+sudo cp -a "./sources" $final_path
+
+# Set permissions
+sudo chown -R $app: $final_path
+
+# Create and restore the database
+ynh_mysql_create_db $dbname $dbuser $dbpass
+ynh_mysql_connect_as $dbuser $dbpass $dbname < ./dump.sql
+
+# Restore configuration files
+sudo cp -a ./conf/nginx.conf "${nginx_conf}"
+
+# Restore php-fpm configuration files
+sudo cp -a ./conf/php-fpm.conf "${phpfpm_conf}"
+sudo cp -a ./conf/php-fpm.ini "${phpfpm_ini}"
+
+# Reload service
+sudo systemctl reload php5-fpm
+sudo systemctl reload nginx
+sudo yunohost app ssowatconf
+
+
+
+#!/bin/bash
+
 # Exit on command errors and treat unset variables as an error
 set -eu
 
@@ -47,7 +128,7 @@ ynh_mysql_connect_as $dbuser $dbpass $dbname < ./dump.sql
 
 # Fix installation directories and permissions
 sudo mkdir -p "${DESTDIR}/logs" "${DESTDIR}/temp"
-sudo chown -R www-data: "$DESTDIR"
+sudo chown -R $app: "$DESTDIR"
 
 # Restore configuration files
 sudo cp -a ./nginx.conf   "$nginx_conf"
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,17 +1,19 @@
 #!/bin/bash
 
-# Exit on command errors and treat unset variables as an error
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
 set -eu
 
-# Get multi-instances specific variables
+if [ ! -e _common.sh ]; then
+  # Get file fonction if not been to the current directory
+  sudo cp ../settings/scripts/_common.sh ./_common.sh
+  sudo chmod a+rx _common
+fi
+# Loads the generic functions usually used in the script
+source _common.sh
+# Source app helpers
+source /usr/share/yunohost/helpers
+
 app=$YNH_APP_INSTANCE_NAME
-
-# Load common variables and helpers
-. ./_common.sh
-
-# Set app specific variables
-dbname=$app
-dbuser=$app
 
 # Source app helpers
 . /usr/share/yunohost/helpers
@@ -22,12 +24,17 @@ path=$(ynh_app_setting_get "$app" path)
 path=${path%/}
 dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
 with_carddav=$(ynh_app_setting_get "$app" with_carddav)
+dbname=$app
+dbuser=$app
 
-# Check destination directory
-DESTDIR="/var/www/$app"
-[[ ! -d $DESTDIR ]] && ynh_die \
-"The destination directory '$DESTDIR' does not exist.\
- The app is not correctly installed, you should remove it first."
+ynh_backup_before_upgrade # Backup the current version of the app
+ynh_clean_setup () {
+  ynh_backup_fail_upgrade # restore it if the upgrade fails
+}
+ynh_abort_if_errors # Active trap pour arrêter le script si une erreur est détectée.
+
+# Init final_path, if ever it got deleted somehow
+final_path=/var/www/$app
 
 # FIXME: jessie-backports is needed for php-net-ldap3
 grep -q -R 'jessie-backports' /etc/apt/sources.list{,.d} || {
@@ -39,9 +46,15 @@ grep -q -R 'jessie-backports' /etc/apt/sources.list{,.d} || {
 ynh_package_install_from_equivs ../conf/${DEPS_PKG_NAME}.control \
   || ynh_die "Unable to install dependencies"
 
-# Create tmp directory and install app inside
-TMPDIR=$(ynh_mkdir_tmp)
-extract_roundcube "$TMPDIR"
+# Create system user dedicace for this app
+ynh_system_user_create $app
+
+# Create final_path directory and install app inside
+sudo mkdir -p $final_path
+extract_roundcube "${final_path}"
+# Change owner by admin for execute composer
+sudo chown -R admin: "${final_path}"
+init_composer "${final_path}"
 
 # Install the new Roundcube version
 sudo php "${TMPDIR}/bin/installto.sh" "$DESTDIR" --force --accept \
@@ -52,39 +65,39 @@ rm -rf "$TMPDIR"
 deskey=$(ynh_string_random 24)
 
 # Copy and set Roundcube configuration
-rc_conf="${DESTDIR}/config/config.inc.php"
-sed -i "s/#DESKEY#/${deskey}/g" ../conf/config.inc.php
-sed -i "s/#DBUSER#/${dbuser}/g" ../conf/config.inc.php
-sed -i "s/#DBPASS#/${dbpass}/g" ../conf/config.inc.php
-sed -i "s/#DBNAME#/${dbname}/g" ../conf/config.inc.php
-sudo cp ../conf/config.inc.php "$rc_conf"
+rc_conf="${final_path}/config/config.inc.php"
+cp ../conf/config.inc.php "$rc_conf"
+ynh_substitute_char "#DESKEY#" "$deskey" "$rc_conf"
+ynh_substitute_char "#DBUSER#" "$dbuser" "$rc_conf"
+ynh_substitute_char "#DBPASS#" "$dbpass" "$rc_conf"
+ynh_substitute_char "#DBNAME#" "$dbname" "$rc_conf"
 
-# Fix installation directories and permissions
-sudo mkdir -p "${DESTDIR}/logs" "${DESTDIR}/temp"
-sudo chown -R www-data: "$DESTDIR"
+# Install files and set permissions
+sudo mkdir -p "${final_path}/logs" "${final_path}/temp"
+sudo chown -R $app: "${final_path}"
 
 # Check if dependencies need to be updated with composer
 if [[ -f ${DESTDIR}/composer.json ]]; then
-  exec_composer www-data "$DESTDIR" update --no-dev --prefer-dist
+  exec_composer admin "${final_path}" update --no-dev --prefer-dist
 else
-  init_composer "$DESTDIR" www-data
+  init_composer "${final_path}" admin
 fi
 
 # Install some plugins manually
-sudo rm -rf "${DESTDIR}/plugins/ldapAliasSync"
-sudo cp -r ../sources/plugins/ldapAliasSync "${DESTDIR}/plugins"
-sudo chown -R www-data: "${DESTDIR}/plugins/ldapAliasSync"
+sudo rm -rf "${final_path}/plugins/ldapAliasSync"
+sudo cp -r ../sources/plugins/ldapAliasSync "${final_path}/plugins"
+sudo chown -R $app: "${final_path}/plugins/ldapAliasSync"
 installed_plugins=" 'ldapAliasSync',"
 
 # Update or install additional plugins
-exec_composer www-data "$DESTDIR" require \
+exec_composer admin "${final_path}" require \
     "johndoh/contextmenu dev-release-2.1" \
     "sblaisot/automatic_addressbook"
 installed_plugins+=" 'contextmenu', 'automatic_addressbook',"
 
 # Guess with_carddav value if empty
 if [[ -z "${with_carddav:-}" ]]; then
-  [[ -f "${DESTDIR}/plugins/carddav/config.inc.php" ]] \
+  [[ -f "${final_path}/plugins/carddav/config.inc.php" ]] \
     && with_carddav=1 \
     || with_carddav=0
   ynh_app_setting_set "$app" with_carddav "$with_carddav"
@@ -92,7 +105,7 @@ fi
 
 # Update or instal CardDAV plugin
 if [[ $with_carddav -eq 1 ]]; then
-  install_carddav "$DESTDIR" \
+  install_carddav "${final_path}" \
     && installed_plugins+=" 'carddav'," \
     || echo "Unable to install CardDAV plugin" >&2
 fi
@@ -101,20 +114,12 @@ fi
 sudo sed -i "s#^\s*// installed plugins#&\n ${installed_plugins}#" \
     "$rc_conf"
 
-# Copy and set nginx configuration
-nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
-sed -i "s@#PATH#@${path:-/}@g"     ../conf/nginx.conf
-sed -i "s@#DESTDIR#@${DESTDIR}/@g" ../conf/nginx.conf
-sudo cp ../conf/nginx.conf "$nginx_conf"
+# Modify Nginx configuration file and copy it to Nginx conf directory
+ynh_nginx_config
 
-# Copy and set php-fpm configuration
-phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"
-sed -i "s@#POOLNAME#@${app}@g"     ../conf/php-fpm.conf
-sed -i "s@#DESTDIR#@${DESTDIR}/@g" ../conf/php-fpm.conf
-sudo cp ../conf/php-fpm.conf "$phpfpm_conf"
-sudo chown root: $phpfpm_conf
-sudo chmod 644 $phpfpm_conf
+# Create the php-fpm pool config
+ynh_fpm_config
 
 # Reload services
-sudo service php5-fpm restart || true
-sudo service nginx reload || true
+sudo systemctl restart php5-fpm
+sudo systemctl reload nginx
